version: '3.8'

services:
  mysql:
    image: docker.io/library/mysql:5.7
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpdocker
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - tpnet

  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin
    container_name: mypma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - tpnet

networks:
  tpnet:
