version: '3.2'
volumes:
  mysql-data:

services:
  node:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "user"
      DATABASE_NAME: "tp2db"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "tp2db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    volumes :
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
